# warning: do not use *tuple* in yaml file

# model 
model_id: SyncNet

# multi-GPUs
use_mGPU: True

# validation
use_validation: False
valid_dataset_root: {
    'video': '/home/leee/data/HDTF/frame-insight',
    'audio': '/home/leee/data/HDTF/mel'
}

# wandb
use_wandb: True
wandb_alert_thres: 1000

# root
train_dataset_root: {
    'video': '/home/leee/data/HDTF/frame-insight',
    'audio': '/home/leee/data/HDTF/mel'
}

save_root: 'train_result/syncnet'

# learning rate
lr_S: 0.00005 # 0.0001

# optimizer 
optimizer: Adam # [Ranger, Adam]
betas: [0.5, 0.999] # default: Adam (0.9, 0.999) / Ranger (0.95, 0.999)

# weight of loss

# hyperparameters
same_prob: 0.2
batch_per_gpu: 32 # 64 (official)
max_step: 400000

# log cycle
loss_cycle: 25
test_cycle: 1000
ckpt_cycle: 10000

# ckpt path
# load checkpoints from ./train_result/{ckpt_id}/ckpt/G_{ckpt_step}.pt
# if ckpt_id is empty, load G_latest.pt and D_latest.pt
# Note that an empty space is None, but None is "None"
load_ckpt: False
ckpt_id: 
ckpt_step:

# syncnet
video_step_size: 5
mel_step_size: 16
img_size: 96
fps: 25